### ISSUE TITLE
Find a way to configure the bridge so that transfers are not possible.

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#12]

**Comment by saschagoebel** [comment]
See https://github.com/trustlines-network/project/issues/421

**Comment by jannikluhn** [comment]
This *should* work by setting the daily payout limit of the foreign chain to zero.

**Comment by jannikluhn** [comment]
There are two daily limits: The daily limit and the daily execution limit. My understanding is that the regular daily limit determines how much can be paid to each of side of the bridge, the execution daily limit how much can be paid out by the bridge contracts. This means for us, that we can cripple the side->main direction by setting the daily execution limit of the foreign bridge contract deployed on the main chain to zero. Reading the code seems to confirm this understanding. I've also tried it out in our testing environment and transfers did not work anymore. However, the bridge validator acts as another layer preventing the transfer here, so this is not entirely conclusive.

If we want to be safe we can also set the zero address as the only validator.

Note that both the ERC-to-ERC bridge and the native-to-ERC bridge explicitly burn and mint tokens, but this feature is not available (yet?) in the native-to-ERC bridge that we would need. Fortunately, as outlined above, this shouldn't be necessary

**Comment by weilbith** [comment]
@jannikluhn did you tried this out practically already?

> Fortunately, as outlined above, this shouldn't be necessary

I think we consider to do so, because the configuration of the limits is a local thing. So if I understand this correctly, it is a local setup of each validators bridge observing threads. Means we can't prevent violations. Therefore burn the tokens would make this as save as we can achieve, right?

**Comment by jannikluhn** [comment]
> @jannikluhn did you tried this out practically already?

Yes:

> I've also tried it out in our testing environment and transfers did not work anymore. However, the bridge validator acts as another layer preventing the transfer here, so this is not entirely conclusive.

> I think we consider to do so, because the configuration of the limits is a local thing. So if I understand this correctly, it is a local setup of each validators bridge observing threads. Means we can't prevent violations. Therefore burn the tokens would make this as save as we can achieve, right?

No, it's a contract setting that can be changed by the owner. We can set it and then set the owner to the zero address. The only problem is then that all other settings are locked as well.

**Comment by weilbith** [comment]
Sry, I missed that. :see_no_evil: 
Okay, so this should be done, since we have such configuration and can apply it to a production setup. :+1:
