### ISSUE TITLE
Document how we create proof for equivocation

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#128]

**Comment by weilbith** [comment]
A new [wiki page](https://github.com/trustlines-network/project/wiki/Report-Malicious-Validator-Function) has been added.

**Comment by weilbith** [comment]
@cducrest please checkout it out and give some feedback. :upside_down_face:

**Comment by cducrest** [comment]
I only did small adjustments

**Comment by weilbith** [comment]
Thanks for the corrections. And adding an example of the array structure is also a good idea. :+1:
