### ISSUE TITLE
Figure out how to handle validator set changes on bridge

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#13]

**Comment by jannikluhn** [comment]
It looks dire: According to Parity's support, it is not possible to add new or update existing contracts via hard forks using the chain spec config file. This means we can't just replace the bridge contract on hard forks.

They're also not aware of a way of reading the current validator set in a contract. This means we can't update the validator set used in the bridge on hard forks.

I can think of 2.5 ways to still achieve this, but they all have issues:

1) Fork Parity and implement the contract replacement feature by ourselves
2) Construct a list of live validators by looking at the block producers of past blocks.
3) Let validators manage the validator set themselves

Option 1 would require us to dig deep into the Parity code, learn to write Rust, and maintain our own fork until they merge it (which might be soon, or might be never).

Option 2 is also hard to implement and adds some conceptual problems:
- we can't access the validator address directly, but only the coinbase address that producers can choose freely
- we only get them indirectly from block headers provided by transactions, that we need to check against block hashes
- we only get them with some delay
- we need to assume that addresses that haven't produced a block in some time are not a validator

Option 3 is what Parity suggested, but it requires us to trust the old validator set even after we've changed it in a fork.

**Comment by cducrest** [comment]
Why can we not call the `getValidators()` function from the validator contract to get the list of validators?
https://github.com/trustlines-protocol/blockchain/blob/master/contracts/contracts/ValidatorSet.sol#L117

This potentially does not solve the problem as the bridge will have to figure out which contract to call, but gets us closer.

**Comment by saschagoebel** [comment]
This would make all chain validators automatically bridge validators. If that's acceptable, we can go that route, yes.

We'd basically just have to make this contracts internal address storage a proxy to the validator contract: https://github.com/poanetwork/poa-bridge-contracts/blob/master/contracts/upgradeable_contracts/BridgeValidators.sol

**Comment by cducrest** [comment]
This is what we want, but the problem remains that if we change the validator set by updating the chain spec file and adding a different contract after a certain block height (https://github.com/trustlines-protocol/blockchain/blob/master/config/trustlines-spec.json#L76), we need to have a way to also inform the bridge contract of this change.

**Comment by saschagoebel** [comment]
When deploying the new validator set contract, we could inform the bridge validator contract of the new address and the activation block.
The bridge validator contract could keep the addresses in a map / array and use the appropriate validator set for the current block number.

Alternatively: Is there any contract or function where we can just look up the currently active validator set contract? Some solidity extension maybe?

**Comment by cducrest** [comment]
Since we do not want a central entity telling the bridge which is the current validator set, we cannot do this. However, we might let the bridge receive a message with origin `systemAddress` that would allow switching the validator set. This function could be called in `finalizeChange()` (https://github.com/trustlines-protocol/blockchain/blob/master/contracts/contracts/ValidatorSet.sol#L127), from the validator contract.

**Comment by saschagoebel** [comment]
According to this thread https://github.com/paritytech/parity-ethereum/issues/9131 the finalizeChange method is called as soon as >50% of all authorities signed a block following the change of the validator set, BUT only for changes. In case the validator set contract is swapped via hard fork, there is no mechanism to detect which contract is the active one.

**Comment by cducrest** [comment]
Except if we mock a set change on the new contract by emitting `initiateChange(currentValidators)`. To be probably tested.

**Comment by weilbith** [comment]
@schmir-at-bb related to you recent changes on our custom home bridge contract, can this issue be considered as closed?

**Comment by schmir-at-bb** [comment]
I'd say the home bridge contract handles the changes well as long as the validator list proxy provides the right values.

**Comment by schmir-at-bb** [comment]
One additional thing we could do is let the home bridge check if the validator set has changed for **every** confirmTransaction call and log an event containing the new set of validators if it changed.

At the moment we plan to periodically check if we are allowed to validate. This is needed when onboarding new validators, since they may start their bridge before they are validators.

We would need to store the last change when the validator set changed in both the proxy and the home bridge in order to make that feasible.

That would give a complete picture on what happened on the home bridge via its logs. At the moment this information is somehow incomplete, since the proxy cannot emit events when the validator set changes.

**Comment by berndbohmeier** [comment]
done for now
