### ISSUE TITLE
Have bridge end2end tests

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#130]
Deploys two chains, deploys the bridge using the deploy script, deploys the reward contract using the deploy script, and make a transfer.

**Comment by weilbith** [comment]
Started to work on the integration of the deployment tool.

**Comment by saschagoebel** [comment]
Pushed the latest dev state to https://github.com/trustlines-protocol/blockchain/tree/feature/bridge-e2e

Currently the deployment fails [here](https://github.com/trustlines-protocol/blockchain/blob/feature/bridge-e2e/bridge-deploy/bridge_deploy/home.py#L105) with an error while calling estimateGas:

```
2019-06-21 15:05:01 UTC jsonrpc-eventloop-0 TRACE rpc  Request: {"jsonrpc": "2.0", "method": "eth_estimateGas", "params": [{"to": "0x86e3DC6e34A7303765f8A3588c855747173C2e83", "data": "0x3ad06d16000000000000000000000000000000000000000000000000000000000000000200000000000000000000000064039cfbca06b36e54dfe30fa004cc5c829b890d"}], "id": 63}.
2019-06-21 15:05:01 UTC jsonrpc-eventloop-0 DEBUG rpc  Response: {"jsonrpc":"2.0","error":{"code":-32016,"message":"The execution failed due to an exception.","data":"Reverted"},"id":63}.
```

I was not able to find any log on what may be wrong. I even changed the underlying solidity code to not do any checks without success.

**Comment by weilbith** [comment]
This is related to the missing EIPs. Using a more recent Parity version, shows a more accurate error message (took me a while to figure this out). Actually they have been already added to the chain specification. You should try to rebuild the nodes first.

**Comment by saschagoebel** [comment]
I checked the EIPs again and even moved EIP98 to a future block, like it's configured in the test chain, but I still get the same error. I rebuilt all containers and there's no additional logging information I can make sense of.

**Comment by weilbith** [comment]
EIP98 starts on block `0` as all others as well...

**Comment by saschagoebel** [comment]
Not in our testnet. But it doesn't make any difference. Does it work for you?

**Comment by weilbith** [comment]
We just talked about the problem. We kinda misunderstood each other. This estimation error is a new one and only occurs when coming to the home bridge initialization. @saschagoebel is working on this, while I continue to fix the tests for trustlines-network/contract-deploy-tools#41 for being able to transfer through the bridge.

**Comment by weilbith** [comment]
PR trustlines-protocol/contract-deploy-tools#42 has been opened. I'm back to fix the gas problem for the home bridge deployment.

**Comment by weilbith** [comment]
PR merged. Waiting for a new version to be published.

Besides I need to add a "wait command" for the message broker. This service needs unpredictable long (observed durations between 30s and 2min) to get up. All other services are waiting for it and do not work unless.

**Comment by weilbith** [comment]
The watcher services can't fetch their events. Start to checkout if their environment is set correct. Probably need to inject the code base and build from local instead of fetching from _DockerHub_.

**Comment by weilbith** [comment]
Signature collection watcher works now. Affirmation watcher needs some work for catching events as well.

**Comment by weilbith** [comment]
A lot more bugs have been fixed, which haven't mentioned here. We are at the point now, that the bridge watcher to home bridge contract works and also the reward contract is used, but the connection seem not to work.

**Comment by weilbith** [comment]
Done by the related PR.
