### ISSUE TITLE
Find out which version of parity to use

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#131]
Find out which parity version to use.
Need at least 2.2.10  for introduction the EIPs.
Need at least 2.3.6 to solve the immediateTransition bug.
Version 2.4.6 seems to disconnect after a timestamp overflow error.

**Comment by schmir-at-bb** [comment]
I would go with the latest release on the 2.3 branch, which at the moment is 2.3.8.
2.4.7 is broken (maybe all of the 2.4 releases), and @cducrest always advocates for using 2.3.7.

The other option is to use a current beta release. I would only try  if we run into problems with 2.3.x 

@cducrest @berndbohmeier @jannikluhn Opinions?

**Comment by cducrest** [comment]
I would vote for 2.3.6 since it never crashed on me, but 2.3.8 should be fine as well.

**Comment by berndbohmeier** [comment]
I am fine with trying 2.3.8

**Comment by schmir-at-bb** [comment]
Actualy 2.3.9 is the latest from the 2.3 series. Sorry for spreading misinformation.

**Comment by cducrest** [comment]
We are going to try out 2.3.6
