### ISSUE TITLE
Investigate which node is making the network crash

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#132]
Find out the source of timestamp overflow. Perhaps a single validator is responsible for all the wrong blocks, find out if the block is actually wrong and unused.

**Comment by cducrest** [comment]
Crashed at block 2707093 http://blockexplorer.trustlines.foundation/blocks/2707093/transactions

**Comment by saschagoebel** [comment]
@cducrest @schmir-at-bb : How sure are we, that this was actually a chain problem and not a problem with the blockexplorer? Do we have additional logs to look into?

I've checked for all 4 blocks the previous and following blocks and
- The timestamps are almost exactly 5 seconds apart
- The validators are in the order they are defined in the chainspec
- There are no uncles in the blocks
- The step values are also correct

eth.events SQL: ```SELECT * FROM block WHERE number IN('2707092', '2707093', '2707094', '2707887', '2707888', '2707889', '2708037', '2708038', '2708039', '2757104', '2757105', '2757106') ORDER BY number```

**Comment by saschagoebel** [comment]
See https://github.com/paritytech/parity-ethereum/issues/10688#issuecomment-503472922

**Comment by schmir-at-bb** [comment]
Bernd already commented on that issue. It looks like system clocks have been off for a bit: https://github.com/paritytech/parity-ethereum/issues/10688#issuecomment-499553861

I do think this issue doesn't need further work.

**Comment by saschagoebel** [comment]
The issue has been fixed in https://github.com/paritytech/parity-ethereum/pull/10720 which is just waiting to be merged.

We have to make sure the validator nodes update the time regularly though. Added documentation in this PR https://github.com/trustlines-protocol/blockchain/pull/172

**Comment by cducrest** [comment]
Closing this because it no longer makes sense.
