### ISSUE TITLE
Track bug report for timestamp overflow error

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#133]
See if we need to send another bug report to parity or if we need to help on an already open issue.

**Comment by cducrest** [comment]
They seem to be aware of it: https://github.com/paritytech/parity-ethereum/issues/10688

**Comment by cducrest** [comment]
I subscribed to their issue and will report to them if I notice something they are not aware of.

**Comment by berndbohmeier** [comment]
I added my findings which versions are still usable.
