### ISSUE TITLE
Write down the EIPs in the config

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#134]
Also decide on fork number, make it fancy or comms will complain
See: https://github.com/trustlines-network/project/issues/497
Also upgrade the E2E tests for monitor (config file)

**Comment by weilbith** [comment]
@cducrest is this issue actually solved? :thinking:

**Comment by cducrest** [comment]
yes.
https://github.com/trustlines-protocol/blockchain/blob/master/config/trustlines-spec.json#L105
