### ISSUE TITLE
Upgrade eth-tester to work with new EIPs

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#135]
When a working version is found, upgrade also other repos
https://github.com/trustlines-network/project/issues/497

**Comment by schmir-at-bb** [comment]
Some PRs have already been opened: 

https://github.com/trustlines-protocol/contract-deploy-tools/pull/38

https://github.com/trustlines-protocol/contracts/pull/203

**Comment by schmir-at-bb** [comment]
https://github.com/trustlines-protocol/py-eth-index/pull/44

**Comment by schmir-at-bb** [comment]
@cducrest Is there a way to configure the plugin to use stpetersburg as evm target via a setting in conftest. How would I do that?

**Comment by cducrest** [comment]
I didn't find a way to do in conftest.
You can have a pytest.ini file with
```
[pytest]
addopts = --evm-version petersburg
```
or you can run pytest --evm-version petersburg
