### ISSUE TITLE
Communicate fork for EIPs

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#136]
Write down all infos about the fork (block nr, reason, time, etc ...) and communicate it to comms so they make a reddit post.

**Comment by cducrest** [comment]
The Trustlines Foundation is planning a hard fork at block number `x` to introduce the EIPs 145, 1014, and 1052. These EIPs were added to the Ethereum main chain as of "Constantinople" upgrade.

### Reasons and timing for the proposed hardfork
We will distribute an update that would fork the Trustlines testnet on block `x` to add new EIPs and keep up to date with improvements of the Ethereum main chain.
This block height is expected to be reached on `xxx`.

### Information for validators using the quickstart script
Validators running watchtower on the trustlines testnet docker image (validators that used the quickstart script) will automatically update to use this new fork. We will push a new docker image for this fork, that will be picked by auto-updaters, on `xxx`.
With this update, the chain-spec file will be modified in order to use a non-reporting `safeContract` instead of a reporting `contract`. As a result, validators will stop automatically sending failing transactions to the validator contract reporting offline validators.
Additionally, the version of parity used by the docker image will upgrade from 2.2.11 to 2.3.9, in order to add more stability to validators node.

### Relevant links
EIP 145: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-145.md
EIP 1014: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1014.md
EIP 1052: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1052.md
trustlines-spec.json:

**Comment by cducrest** [comment]
Aimed timestamp: 1560333600 (12/06/2019 12:00 UTC+2)
Aimed block nr = 2820282

**Comment by andfletcher** [comment]
this should be done @cducrest
