### ISSUE TITLE
Create static validator set contract

### ISSUE THREAD

**Issue by andfletcher** [trustlines-protocol/blockchain#140]
Placeholder for the upcoming Proxy Contract.

See https://github.com/poanetwork/poa-bridge-contracts/blob/master/contracts/upgradeable_contracts/BaseBridgeValidators.sol for the interface

**Comment by cducrest** [comment]
Design:
One `ValidatorProxy.sol` contract for the chain, represents the state of the validator set on-chain.
One `BridgeValidators.sol` contract that provides the api functions necessary to the bridge regarding validators, this allows us to not modify the bridge and have to deal with forking the poabridge repo. This also allows us to have a clean `ValidatorProxy.sol` contract not related to the bridge but useable by anyone wishing to get the validator set on chain.
