### ISSUE TITLE
create empty foreign bridge contract

### ISSUE THREAD

**Issue by andfletcher** [trustlines-protocol/blockchain#141]
This will later be extended with the burn functionality.

For now it's just some address we can send the tokens to.

**Comment by weilbith** [comment]
@saschagoebel what is your intention by this task? Don't we plan to use [this contract](https://github.com/poanetwork/poa-bridge-contracts/blob/master/contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol)?

**Comment by saschagoebel** [comment]
No, we're using a minimal own implementation that just burns the tokens from time to time.

**Comment by weilbith** [comment]
Okay. Do we actually know which features are actually needed to make the bridge observing clients working? Their structure is not really transparent.

**Comment by saschagoebel** [comment]
We hope it's just the transfer event, but the e2e test will show ;-)
