### ISSUE TITLE
Get an auction running to write documentation

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#164]
Auction should be displayed on the website
Starting price 1 eth
Duation 1 day
min validators: 3
the rest does not matter
whitelist: 0xD1F5615cDDdada4e497cd105daFC1884161147e6

**Comment by schmir-at-bb** [comment]
@come do you still need that? it looks like you used our 'failed test auction' for the documentation.

**Comment by cducrest** [comment]
yes, I did.
