### ISSUE TITLE
Put all deploy tools in one folder

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#173]
Make sure cirecleci is updated

**Comment by schmir-at-bb** [comment]
Are you fine with using `tools` as a name for the  directory? @cducrest @saschagoebel  @weilbith

**Comment by saschagoebel** [comment]
I'd have used ```deploy```, but ```tools``` is fine as well. Alternatively: ```cli```

**Comment by weilbith** [comment]
- `deploy` :+1: 
- `tools` :man_shrugging: 
- `cli` :-1:

**Comment by schmir-at-bb** [comment]
I've opened a PR  moving the auction-deploy to the tools directory. I don't like deploy. It prevents us from putting some other kind of tool in there.
`deploy-tools` is not an option, because we have the contract-deploy-tools package, which uses `deploy_tools` as python import package name.

**Comment by saschagoebel** [comment]
I'm fine with either.
