### ISSUE TITLE
Combine and extend bridge deploy commands

### ISSUE THREAD

**Issue by weilbith** [trustlines-protocol/blockchain#194]
The bridge deployment tool does deploy and initialize the home bridge contract in a different target than the reward contract. Due to #193 they must be combined, since their deployment addresses must be put into each others initialization functions.

**Comment by saschagoebel** [comment]
Also note that the BridgeValidators contract needs to be deployed separately via ```bridge-deploy deploy-validators ...```with the ValidatorsProxy as a parameter.

**Comment by weilbith** [comment]
Is this related to combine the home bridge and reward contract targets or for the end-to-end tests?

**Comment by saschagoebel** [comment]
Probably more #193, but as it's a vital part of the bridge itself, it could also be integrated into "deploy the whole thing"
