### ISSUE TITLE
Home bridge contract stores validators confirmations

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#232]
For each pending transfer, the home bridge contract stores which validator confirmed the transfer and the number of confirmations.
Bridge emits event `Confirmation(transaction_hash, validator_address, amount, recipient)` when receiving a confirmation.

**Comment by schmir-at-bb** [comment]
We don't use a bitfield and haven't optimized the gas cost yet. Other than that it's done.
