### ISSUE TITLE
Home bridge contract sends coins after enough confirmation

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#233]
The home bridge contract will send the coins after collecting enough confirmations and emit an `TransferCompleted(transaction_hash, amount, recipient)` event. It will also clean up its storage when possible.

**Comment by jannikluhn** [comment]
I'm not sure if we should cleanup successful transfers. Keeping them would act as a safeguard against confirming a transfer multiple times in case validators forget about the past.

**Comment by cducrest** [comment]
I am not sure what the data structure in the home bridge contract is at that time, but we could delete who confirmed the transfer and still keep that the transfer has been confirmed. That may save gas costs for the final transaction that may be sending fees to the participating validators. I may also be impossible.

**Comment by schmir-at-bb** [comment]
It sends coins, but we haven't optimized gas usage.
