### ISSUE TITLE
Confirmation worker does not send unnecessary confirmations

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#235]
When triggered by a `transfer` event, the confirmation worker does not send a confirmation if the transfer was already completed or if the validator already sent a confirmation.

**Comment by weilbith** [comment]
Just as an update, since this is so empty, this is waiting for the planner module. This module has been rewritten multiple times, but should be in the final phase now. If I'm correct, Jannik is already on the preparation to integrate all modules with each other.
