### ISSUE TITLE
Home bridge fetcher worker stores confirmation state

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#236]
The home bridge fetcher worker needs to store in the internal state whether a bridge transfer is already confirmed by the validator and whether it is already complete by looking at `Confirmation` and `TransferCompleted` events

**Comment by jannikluhn** [comment]
Interpreting this as

> Make sure a transfer is not already completed before sending a confirmation transaction

and working on it.

**Comment by jannikluhn** [comment]
See https://github.com/trustlines-protocol/blockchain/pull/259#pullrequestreview-266562461 for a possible approach and discussion.

I'm not working tomorrow, so if someone feels like it please pick it up. If not I'll continue with this on Monday.
