### ISSUE TITLE
Upgrade Web3.py to 5.0.0b4

### ISSUE THREAD

**Issue by saschagoebel** [trustlines-protocol/blockchain#262]
As discussed we should update Web3.py to a recent version because of the ChainId Bug that has been fixed in version 5.0.0b3.

Sadly there's some compatibility problem with ethpm which I was not able to resolve.

Steps to reproduce
- blockchain-repo branch live-test-fixes
- change web3 to 5.0.0b4 in constraints.txt
- cd tools/bridge
- make test

**Comment by schmir-at-bb** [comment]
I've opened a PR: https://github.com/trustlines-protocol/blockchain/pull/263

Make sure you uninstall ethpm first. Details are in the PR.
