### ISSUE TITLE
Put timestamps on event queue

### ISSUE THREAD

**Issue by jannikluhn** [trustlines-protocol/blockchain#284]
The confirmation planner needs to know at what time events happened. Block numbers are not enough for this as they can't be compared across different chains. We also need to know about the absence of events. It seems natural to put this information on the event queue.

Technically, events don't have a timestamps, but the blocks in which they were raised have. In web3.py we can access this with something like `w3.eth.getBlock(event.blockHash).timestamp` (note that all events in a block share the same timestamp).

It's probably a good idea to only put objects of a single type on the event queue to avoid confusion.

One approach would be to transform the `event_queue` to an `event_batch_queue` and define batch as a tuple of a timestamp and a list of events (the idea being to group all events from a single block in one batch):

```
class EventBatch(NamedTuple):
    timestamp: int
    events: List[dict]
```

An alternative would be to define use "artificial" events that only contain a timestamp and no actual event:

```
class MaybeEvent(NamedTuple):
    timestamp: int
    event: Optional[dict]
```

**Comment by schmir-at-bb** [comment]
> The confirmation planner needs to know at what time events happened. Block numbers are not enough for this as they can't be compared across different chains

Why? I can think of a solution that doesn't need a timestamp.

**Comment by jannikluhn** [comment]
See #272 to related discussion

**Comment by jannikluhn** [comment]
After discussion we've decided to ignore event timestamps for simplicity.
