### ISSUE TITLE
Introduce artificial event

### ISSUE THREAD

**Issue by jannikluhn** [trustlines-protocol/blockchain#287]
The confirmation task planner needs to know if we're synced or not. One way to do this is to make the event fetcher put an "artificial event" on the queue that signals the fact that we are in sync. The artificial event needs to have a timestamp as the sync status is temporary. It needs to be possible to distinguish between normal and artificial events (e.g. via an `isinstance` check). The timestamp should probably (?) use the local clock, not the timestamp in the last block as we get a much better resolution.

**Comment by weilbith** [comment]
I have something super simple, since this is not much logic (~5 loc). But @jannikluhn will have a quick meeting soon to discuss the further handling and interaction of the planner.

**Comment by weilbith** [comment]
There are some problems with `gevent` on the tests. I have to discuss my solution of a monkey patch with Ralf.

**Comment by schmir-at-bb** [comment]
The gevent problems will be solved by #292
