### ISSUE TITLE
Investigate what needs to be done to make bridge more robust

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#300]

**Comment by berndbohmeier** [comment]
What is the status on this @schmir-at-bb?

**Comment by schmir-at-bb** [comment]
We have already better logging and a separation of web3 calls and the we do retry web3 calls. We will retry those calls till forever.

https://github.com/trustlines-protocol/blockchain/issues/367 is still an open issue, but is easy to solve.

We do not have any kind of 'back pressure' for fetching events (i.e. we may load all of the events from the foreign chain into memory, when the home chain hangs). This shouldn't be a serious issue, at least not at the start.

I think it's in a state where we could put this into production and then see what comes up.

**Comment by berndbohmeier** [comment]
Are we able to handle that the home or foreign chain nodes are unavailable/unresponsive for a while?

If you think everything is done, please close this.

**Comment by schmir-at-bb** [comment]
> Are we able to handle that the home or foreign chain nodes are unavailable/unresponsive for a while?

yes, we will retry requests in that case.
