### ISSUE TITLE
Include bridge into the bridge via the quickstart script

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#302]
The bridge should also be set up by the quickstart script. 
The default option should be that the bridge is setup. 

We probably have to consider that we have to change our setup to use a docker compose file.

**Comment by weilbith** [comment]
At the moment the bridge client expects a decrypted, hex-encoded private key within the configuration. The setup of the bridge client is placed after the import/creation of the validator key for _Parity_. Asking the user (again) for the key is odd. Especially if we just created a new file for him, this would be the worst user experience. 

So we could take the existing key store and password to extract the private key and copy it to the configuration of the bridge. Therefore I would extend the `quickstart` tool. Anyways the usage with docker would be semi-nice.
The maybe easier to apply version of the former approach would be to extend the earlier private key creation/import functionality. Therefore it could store a third file with the plain private key. 
The alternative solution is to make the bridge client working with a key and password file and reuse the existing setup as it is. This would then require a shared volume between the _Parity_ and bridge container.

To be honest I'm absolutely not sure what the best solution is to go for. Maybe another alternative is even better. Open for input.

@schmir-at-bb

**Comment by berndbohmeier** [comment]
Can we not just read it from the keyfile. I think putting an unencrypted private key into a configuration file is not a good solution. The password can be read from a another file, the same way how parity does. it.

**Comment by weilbith** [comment]
That's one solution I proposed, yes. Then I would open an issue for the bridge to add this feature. Because at the moment the bridge only works with such a decrypted key.
