### ISSUE TITLE
Remove misleading and wrong comment

### ISSUE THREAD

**Issue by schmir-at-bb** [trustlines-protocol/blockchain#305]
The comment in https://github.com/trustlines-protocol/blockchain/blob/master/tools/bridge/bridge/confirmation_sender.py#L62 is wrong!

Only Transfer events are put onto this queue.

**Comment by jannikluhn** [comment]
The link points to an empty line, can you update it please @schmir-at-bb ?

**Comment by schmir-at-bb** [comment]
I will take care of this.
