### ISSUE TITLE
send_confirmation_transactions drops transfer events to confirm when not (yet) a validator

### ISSUE THREAD

**Issue by schmir-at-bb** [trustlines-protocol/blockchain#306]
There should be a better way to handle that situation. Maybe we should wait until we become a validator.

**Comment by weilbith** [comment]
@schmir-at-bb is this equivalent to #276?

**Comment by jannikluhn** [comment]
Suggested approach: On startup, run the event fetchers, but not the confirmation planner and sender. In addition, run a greenlet that periodically checks if we are a validator or not. Once the check succeeds, launch confirmation planner and sender.

Does this make sense?

**Comment by schmir-at-bb** [comment]
This will work. If the confirmation planner is not running, the queues will be filled with events and no one is consuming events.

I would try to start everything like it is now and keep a flag in the TransferRecorder[1], if we're already allowed to confirmTransfers. The recorder would return an empty list in the pull_transfers_to_confirm() if we're not yet allowed to confirm transfers. Nevertheless the state in the recorder will be able to catch up with the current state of the chain. We should make sure that completed transfers don't stay in the recorder in order to not waste memory (even when we are not a validator yet).


Contrary to what I said in the meeting, I would not put this onto a queue, since I think it's special enough that we could also just call a method that does set this flag.

So, please start a greenlet that waits for the validator status to become true, sets this flag, and then still watches the validator status. If we stop being a validator, it's game over and we could probably abort the program.

[1] One could argue that we should use another name for the TransferRecorder then. But I'm fine with living with a bit badly named stuff.
