### ISSUE TITLE
bridge: Initialize loggers on the module level

### ISSUE THREAD

**Issue by schmir-at-bb** [trustlines-protocol/blockchain#311]
We should initialize the loggers on the module level instead of putting them into some class.

**Comment by weilbith** [comment]
I'm confused. I just pulled the `master` and searched for `logging.getLogger()`. Except the `event_fetcher` all module initialize their logger at the top level. And the event fetcher is intended to be like that.
@schmir-at-bb can this issue be closed? Was it part of a bigger PR and has been forgotten or..?

**Comment by weilbith** [comment]
@schmir-at-bb :bell:

**Comment by schmir-at-bb** [comment]
I removed some of them already, but in the meantime jannik introduced more of them.
