### ISSUE TITLE
bridge: Fix dependency declaration, switch to setup.cfg based configuration

### ISSUE THREAD

**Issue by schmir-at-bb** [trustlines-protocol/blockchain#314]
tools/bridge/setup.py fails to declare the needed dependencies. We should fix that so that a installation with pip could have a chance to succeed.

Also, please start using setup.cfg based configuration. The tools/quickstart script folder already uses that (look at setup.py and setup.cfg there).

**Comment by weilbith** [comment]
@schmir-at-bb should I get rid of the `setup.py` at all? I would love to. I guess `pyproject.toml` is one step too far for the moment.
