### ISSUE TITLE
Publish bridge client to PyPi

### ISSUE THREAD

**Issue by weilbith** [trustlines-protocol/blockchain#317]
See the discussion at PR #313

**Comment by weilbith** [comment]
I would block this until we decided branches to use for the Docker image. The argument is that we probably like to publish to PyPI with the same branch filters.

**Comment by weilbith** [comment]
For the docker image we do now publish the following versions:
- `bridge-next:master`
- `bridge-next:pre-release`
- `bridge:release`
- `bridge:latest`

Each version except the `latest` tag also has a second version with the post-fixed _CircleCI_ run number, while the previous list is always updated by the last push.
I'm not sure if we should aim to emulate the same for a PyPI package. A single release version would be enough in my opinion.

**Comment by schmir-at-bb** [comment]
We should release with major.minor.version on pypi.

In the other repos we use setuptools_scm to have an automatic version from the git tag. That won't work in the blockchain repo without further thinking. I would as a first solution manually maintain the version for now (maybe with the help of bumpversion)

**Comment by weilbith** [comment]
> We should release with major.minor.micro on pypi.

That's what I meant with `A single up-counting release version...`. Was not good phrased. Just PEP396.

>  I would as a first solution manually maintain the version for now (maybe with the help of bumpversion)

Well, so this issue can be closed until we have a first production version? :thinking:

**Comment by schmir-at-bb** [comment]
> Well, so this issue can be closed until we have a first production version? 

no, of course not
