### ISSUE TITLE
Remove dotfiles module

### ISSUE THREAD

**Issue by schmir-at-bb** [trustlines-protocol/blockchain#323]
The dotfile module is way too creative in its search for a .env file. It wasted half an hour of my life.

My suggestion is to remove it. If you want to set environment variables you can do so with the envdir program, which is part of the daemontools package or can be installed with 'pip install envdir'

environment variables are then set via creating files in a directory:
e.g.
```
mkdir validator-1
echo "0x00fad...." > validator-1/VALIDATOR_PRIVATE_KEY
echo DEBUG >validator-1/LOGLEVEL
envdir ./validator-1 tlbc-bridge -c config.toml
```

@saschagoebel  Are you fine with that?

**Comment by saschagoebel** [comment]
I'm pretty sure this will waste half an hour of somebody else's life, but yeah, I have no hard feelings as long as I can configure my dev environment.

Put that example in the Readme, maybe. 👍

**Comment by schmir-at-bb** [comment]
> I'm pretty sure this will waste half an hour of somebody else's life

If you think we're wasting half an hour of your life, I'm fine with keeping it. But we have to make sure that it's easy to understand where it is searching for the .env file (and probably log which file it is reading).

**Comment by saschagoebel** [comment]
As said, I'm fine with this solution as well. It's not as straightforward for me personally, but as long as it's documented I can work it out.

We should keep in mind that for docker compose we will still need a single .env file or add each variable manually. See https://docs.docker.com/compose/compose-file/#env_file

@jannikluhn Maybe put a link to https://envdir.readthedocs.io/en/latest/usage.html in the readme

**Comment by saschagoebel** [comment]
As stated in https://pypi.org/project/python-dotenv/ we could also just pin the path to the bridge folder or make it a cli parameter like this:

```python
# OR, explicitly providing path to '.env'
from pathlib import Path  # python3 only
env_path = Path('.') / '.env'
load_dotenv(dotenv_path=env_path)
```

**Comment by schmir-at-bb** [comment]
You can also use 'dotenv run tlbc-bridge' similar to envdir, so you can keep on using the .env files.

I think there's very little reason then to keep this inside tlbc-bridge.

**Comment by saschagoebel** [comment]
That actually sounds like a very nice solution to me which gives us the more widely used file format and the control of explicitly saying which file to use.

So remove dotenv from the code, keep the .env.example (optional) and document how to use CLI dotenv, right?

**Comment by schmir-at-bb** [comment]
> So remove dotenv from the code, keep the .env.example (optional) and document how to use CLI dotenv, right?

I would be fine with that.

**Comment by schmir-at-bb** [comment]
@jannikluhn can you please update the PR to do that? (or raise concerns if you have them)

**Comment by jannikluhn** [comment]
No concerns, I just thought this was done already. But I guess I can add a sentence or two to the readme.

**Comment by schmir-at-bb** [comment]
I thought the .env file was gone. If that's not the case sorry for the noise and feel free to merge.
