### ISSUE TITLE
Set compile optimization runs for bridge

### ISSUE THREAD

**Issue by weilbith** [trustlines-protocol/blockchain#326]
By the "research" of trustlines-network/project#630 to find the optimum of optimization runs when compile the contract (regarding gas costs), the feature to configure the runs has been added by trustlines-protocol/contract-deploy-tools#59. According to the update of the deploy tools dependency (trustlines-protocol/project#631) it makes sense to apply this for the bridge as well.

**Comment by weilbith** [comment]
Regarding the home bridge, the deployment costs on the _Trustlines_ chain should not matter. But  the function calls (confirmations) should be cheap. I found the maximum of optimization at `5000` runs. More runs do not improve anymore. Consider that the number of bridge transfers is big and each one needs to be confirmed by many validators, I think this is a good way to go.

For the foreign bridge this is slightly different. After deployment, the only calls are to burn the tokens. This must not happen too often and is not necessary at all for the functionality of the bridge. But the costs on the _Ethereum_ mainnet must be considered. Thereby less optimization runs would lead to less deployment costs. Unfortunately by the current `Makefile` all contracts are compiled together. This could be split up, but costs work. The difference of deployment costs for the foreign bridge contract differ in maximum (1 run to 5000 runs) by `23.962` gas. Using an average amount of 6GWei this would mean `<0.03$` additional costs by the current market price (`0.27$` total cost prediction).

@andfletcher I would argue it is not worth the work to split the compilation for this less amount of additional cost. Do you agree? If so I would just configure to optimize for 5000 runs to be consistent with the home bridge. In favor the token burn functions calls are marginal more cheaper (really not countable with 50 gas units).

**Comment by andfletcher** [comment]
@weilbith yes i agree
