### ISSUE TITLE
Audit bridge contract

### ISSUE THREAD

**Issue by weilbith** [trustlines-protocol/blockchain#355]
- Identify most qualified colleagues
- send them a link to the documentation (trustlines-protocol/project#639)
- collect feedback
(- schedule meeting to create further tasks by the feedback)

**Comment by weilbith** [comment]
We will go for Yoichi and Karl again. @schmir-at-bb announced to write them a mail later this day.

**Comment by weilbith** [comment]
Move to `In Progress` because Ralf sated in the daily that he has already notified them.

**Comment by schmir-at-bb** [comment]
I've started collecting the feedback here: https://github.com/trustlines-protocol/blockchain/issues/425

**Comment by berndbohmeier** [comment]
Done
