### ISSUE TITLE
bridge: wait for chain to have reached the start block before doing sanity checks

### ISSUE THREAD

**Issue by schmir-at-bb** [trustlines-protocol/blockchain#368]
tlbc-bridge should wait for the chain to have reached the start block before it is doing it's sanity checks. Otherwise the program will just abort, which is a bad experience for users setting up the system with the quickstart script.

**Comment by jannikluhn** [comment]
I would say we don't need this for the home chain as everything will be deployed at genesis (at least it could, not sure what our plan is here).

For the foreign chain it could make sense. We could also add another config option `token_contract_deployment_block_number` as `start_block_number` can be even later. But I don't know if it's worth it.

**Comment by schmir-at-bb** [comment]
It was already a problem for me during testing and it won't hurt if we do this for both chains.

**Comment by schmir-at-bb** [comment]
signal handling should still work and we could already start the webservice when waiting for this to happen. Also it should be clear that it's waiting from looking at the logs.

**Comment by schmir-at-bb** [comment]
@jannikluhn  Can you take care of this?
