### ISSUE TITLE
Handle bridge audit feedback

### ISSUE THREAD

**Issue by schmir-at-bb** [trustlines-protocol/blockchain#425]
Feedback from Karl:
```
I've had a look at the two bridge contracts. They look fine, but I've
collected a few remarks below. Since the subject says "audit of bridge
contracts", I didn't look in detail at any other contracts. Let me know
if I should do that.

## General

The short summary of the purpose of each contract like the ones you
wrote in this mail would make a nice comment at the top of each
contract.

## ForeignBridge.sol

I assume that you deploy the ForeignBridge and make sure that the given
token is indeed one deployed from `TrustlinesNetworkToken.sol`.

## HomeBridge.sol

According to https://ethereum.stackexchange.com/a/39302/49987 , the
delete in purgeConfirmationsFromExValidators is not necessary and can
be removed to save gas.

Why is _confirmTransfer prefixed by an underscore, but
requiredConfirmationsReached isn't?

getNumRequiredConfirmations can overflow for astronomic numbers of
validators. But that's just a theoretical problem.

Why are the confirmingValidators payable? They don't receive any funds
in the HomeBridge contract.

confirmTransfer and reconfirmCompletesTransfer share half of their code
(most assertions + transferStateId hashing). They could be pulled out
into a shared function or at least be formatted and ordered the same
way to make it easier to compare both. The only difference I could find
is the "must be validator to confirm transfers" requirement, which
makes sense.
```

**Comment by schmir-at-bb** [comment]
> The short summary of the purpose of each contract like the ones you
> wrote in this mail would make a nice comment at the top of each
> contract.

I may add a commit later with these short summaries.

> According to https://ethereum.stackexchange.com/a/39302/49987 , the
> delete in purgeConfirmationsFromExValidators is not necessary and can
> be removed to save gas.

f53d0266d5ed4f925ab56fb47302211345f46e99 removes the delete.

> Why are the confirmingValidators payable? They don't receive any funds
> in the HomeBridge contract.

c01c797de780a22bc5d2f4fcff0c3401f2375a9c makes them non-payable.

> getNumRequiredConfirmations can overflow for astronomic numbers of
> validators. But that's just a theoretical problem.

I would not handle that, because it's only theoretical problem.

> confirmTransfer and reconfirmCompletesTransfer share half of their code
> (most assertions + transferStateId hashing). They could be pulled out
> into a shared function or at least be formatted and ordered the same
> way to make it easier to compare both. The only difference I could find
> is the "must be validator to confirm transfers" requirement, which
> makes sense.

I wanted to make reconfirmCompletesTransfer a view and therefore cannot call into purgeConfirmationsFromExValidators.  This was a last minute change, I might have written it differently otherwise. At this point however, I would not change it.

**Comment by berndbohmeier** [comment]
Feedback of Yoichi, he found no critical problems. 
https://docs.google.com/document/d/1bWVE-ie7mPPDr-j-yabL4R8eQQdr0MKzCJG3FCChkyg/edit#heading=h.o2k1hi3h1y68

**Comment by berndbohmeier** [comment]
Tasks for yoichi:
Finding 1 todo
Finding 2 Document transfer, transferFrom and approve. Especially document the spacial behavior of MAX_UINT
Finding 3 Check
Finding 4 Rename, but check if it used in the monitor or the proxy contract uses it
Finding 5 ignore
Finding 6 ignore
Finding 7 Check if the removal reduces the gas costs
Finding 8 Make all internal function start with _s
Finding 9 Check
Finding 10 Write down issue about this

**Comment by cducrest** [comment]
check finding 4 and 9 if you wish @berndbohmeier, otherwise close it.

**Comment by andfletcher** [comment]
Finished
