### ISSUE TITLE
Test if quickstart setup survives update

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#442]
We should check that a setup including

- monitor
- netstats

survives an update of the blockchain image. 
For updating the image will be stopped, and we have to check, if the monitor and netstats handle that properly.

**Comment by berndbohmeier** [comment]
Currently it seem like the bridge does not survive an update 
```
time="2019-10-08T14:33:52Z" level=info msg="First run: 2019-10-08 14:38:52 +0000 UTC" 
time="2019-10-09T12:48:58Z" level=info msg="Found new trustlines/bridge-next:master image (sha256:a2117579db7cd266ecc7c635a9f3601b51a22039b363e99d55ceaef283a8457c)" 
time="2019-10-09T12:49:01Z" level=info msg="Stopping /bridge-client (4c438d3604bc6bb15d8867673977713eefa08213d2a7d1d465b7db8d47a51f7d) with SIGTERM" 
time="2019-10-09T12:49:03Z" level=info msg="Creating /bridge-client" 
time="2019-10-09T12:49:03Z" level=error msg=""stop timeout" requires API version 1.25, but the Docker server is version 1.24"
```
Looks like a too old docker version.

**Comment by berndbohmeier** [comment]
The reason seems to be a too old api version. Watchtower defaults to 1.24

**Comment by weilbith** [comment]
@berndbohmeier can you test this again with the recent `watchtower` update (#461)?

**Comment by weilbith** [comment]
See [this comment](https://github.com/trustlines-protocol/blockchain/issues/441#issuecomment-545340519) of #421.
