### ISSUE TITLE
Investigate potential validator contract bug

### ISSUE THREAD

**Issue by jannikluhn** [trustlines-protocol/blockchain#446]
In block #4321702, validator 0x2AeAB6d45754831f88670eb28E86861BB7bA7de2 has been removed from the validator set. The validator set contract should still remember that this address used to be a validator. However, calling `getValidators()` with an earlier block number using the block explorer (https://explorelaika.trustlines.foundation/address/0x7562f6fbfd211ce9896839b5062d2ba16b839e8c/read_contract) appears to only return the current set.

**Comment by berndbohmeier** [comment]
We checked, and this seems to be a bug of blockscout
