### ISSUE TITLE
Check possible bug in ValidatorSet contract

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#449]
On block 4321702 we attempted to remove the validator 0x2aeab6d45754831f88670eb28e86861bb7ba7de2 by proving its aquivocation, and the finalize to throw him out seems to be have called in block 4321715. 

When we query for the validator sets on the epochs 4321715 and 3180823 it seems that he was not a validator even before. To find out if this is a bug in the blockexplorer or the actual contract, we should directly query for the validators at block 3180823 via the deploy tools. 

TODO:
 - use `deploy-tools call` to query the validators at 4321715 and 3180823 and check if he was a validator in 3180823 but not anymore in 4321715

Please post the outcome here.

**Comment by weilbith** [comment]
With the `deploy-tools`:

`getValidators(3180823)`
- 0xfd8ef30d102af392a5dcfefb06a2e91fbc6f564
- 0x27e6925dd78fabcc9d95da178f9ebb986fa66fdb
- 0x2aeab6d45754831f88670eb28e86861bb7ba7de2
- 0x3150ff61dbe459158615e519250d5a92029d008e
- 0x557143ab458f77da5e99a0de7060ab4037a8adbb
- 0x640d34e204be6cbf8846d68c797971aaa4f91a98
- 0x6c2c0005dbe0f061db93949dd4c876bf3c9bbe5e
- 0x70f264a331a9c3b3248537acf2470d963be741e3
- 0x73d90068c48f2fa8f408f93babd9d8787fe1565f
- 0x7ccb24b3900562d861faa166de1a86ec0e14d0b9
- 0x864123e2747676b69abc4152b3c5bb7c6dbf66e0
- 0x876ac3250fb8cebe6e33b7dfa64fb25b18795f95
- 0x881f68fb5d33fba220b9e98d31526ed1b76cec7a
- 0xa278ce59851441faf42070468d713d1389da0183
- 0xb01b4f67d87b98cb1edb1572b1a3cda3191320a6
- 0xb2158af1a63eb0a0c08bfe5e4563f0875515d065
- 0xc8fce36cced702809203c9121ee6767a376786cc
- 0xd37e3ea1c3fc463b82f45be7933ab975aadf1081
- 0xd3a22ca447f3f0b1b911b06034438bb2629af00e
- 0xe399d154168b8e9043589d4e8128d07f63c75d78
- 0xeeae5b16b091d9bc57ef4d05e48b78e2d119d292
- 0xf35960302a07022aba880dffaec2fdd64d5bf1c1
- 0xf36e2fb50f87944a620caf796c248404850c708b
- 0xf7921f0bca54d81692656d357f88d51effd9e45a
 
`getValidators(4321715)`
- 0xfd8ef30d102af392a5dcfefb06a2e91fbc6f564
- 0x27e6925dd78fabcc9d95da178f9ebb986fa66fdb
- 0x3150ff61dbe459158615e519250d5a92029d008e
- 0x557143ab458f77da5e99a0de7060ab4037a8adbb
- 0x640d34e204be6cbf8846d68c797971aaa4f91a98
- 0x6c2c0005dbe0f061db93949dd4c876bf3c9bbe5e
- 0x70f264a331a9c3b3248537acf2470d963be741e3
- 0x73d90068c48f2fa8f408f93babd9d8787fe1565f
- 0x7ccb24b3900562d861faa166de1a86ec0e14d0b9
- 0x864123e2747676b69abc4152b3c5bb7c6dbf66e0
- 0x876ac3250fb8cebe6e33b7dfa64fb25b18795f95
- 0x881f68fb5d33fba220b9e98d31526ed1b76cec7a
- 0xa278ce59851441faf42070468d713d1389da0183
- 0xb01b4f67d87b98cb1edb1572b1a3cda3191320a6
- 0xb2158af1a63eb0a0c08bfe5e4563f0875515d065
- 0xc8fce36cced702809203c9121ee6767a376786cc
- 0xd37e3ea1c3fc463b82f45be7933ab975aadf1081
- 0xd3a22ca447f3f0b1b911b06034438bb2629af00e
- 0xe399d154168b8e9043589d4e8128d07f63c75d78
- 0xeeae5b16b091d9bc57ef4d05e48b78e2d119d292
- 0xf35960302a07022aba880dffaec2fdd64d5bf1c1
- 0xf36e2fb50f87944a620caf796c248404850c708b
- 0xf7921f0bca54d81692656d357f88d51effd9e45a

The diff is the following address:
`0x2aeab6d45754831f88670eb28e86861bb7ba7de2`

This is the validator that has been removed.

**Comment by berndbohmeier** [comment]
Okay, so it seems to be a bug in blockscout then. Thanks for investigating.
