### ISSUE TITLE
Push and use bridge release tag in docker-compose file

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#464]

**Comment by weilbith** [comment]
Status:
- `trustlines/tlbc` repository does not exist and is actually named `trustlines/tlbc-node` as I know
- `trustlines/bridge-release` repository does not exist and is probably a typo and `release` means the tag (as for the `laika` composition)
- all other repositories and their `release` tag exist

The composition for `laika` works well as it is (at least for `docker-compose pull`). I'll go to open a small PR adjusting both issues.

**Comment by weilbith** [comment]
I just realized that the `trustlines/tlbc-node` repository is empty. @schmir-at-bb are there already any efforts to adapt the _CircleCI_ flow and push to the according branches/tags?

**Comment by weilbith** [comment]
So the _CircleCI_ configuration is already adopted to the new name. Therefore the release version must be just pushed.
