### ISSUE TITLE
Configure & Deploy BlockRewardContract for PoA Bridge

### ISSUE THREAD

**Issue by saschagoebel** [trustlines-protocol/blockchain#47]
## Description

**As a user I want to be able to**
Transfer ERC20 Tokens to the Trustlines Sidechain and generate native Coins on the Sidechain.
Inside the PoA Network Bridge Test Environment

**So that I can**
Transfer Trustlines Tokens and evaluate the PoA Bridge

## Acceptance Criteria

- [x] PoA Validator Deployed
- [x] BlockRewardContract configured to use PoA Addresses
- [x] BlockRewardContract Deployed
- [x] BlockRewardContract Activated via chainspec

## Related story / issue
- https://github.com/trustlines-protocol/blockchain/issues/9#issuecomment-484578874 for RewardContract Details (3rd paragraph)

## Reviewer
-

**Comment by weilbith** [comment]
The original POA `RewardByBlock` contract depends on complex proxy storage, key manager and eternal storage dependencies. This is part of the big [poa-network-consensus-contracts](https://github.com/poanetwork/poa-network-consensus-contracts) repo and not the bridge itself. We only need parts of that which are much more connected to other components we are not using or have our own one (like validator set contract). The deployment of this is a huge script also containing more than we need. The deployment of the reward contract is related to their developer set contract, the storage proxies are filled etc.
To keep it easy on tests, a derived contract has been written which only needs a single `init` call for all necessary information. It implements the interface for Parity as well as the bridge. The contract has been verified to work with Parity as reward contract. The bridge functionality has been tested via unit tests, but not with a deployed bridge, which is the next step now.

**Comment by jannikluhn** [comment]
The original reward contract with slight modifications has been deployed and is working

**Comment by weilbith** [comment]
We still consider to use an own implementation, since we will need to extract their contract anyways. Therefore we can also simplify their Solidity implementation to get rid of the unnecessary dependencies.

**Comment by weilbith** [comment]
@jannikluhn the first to requirements can be stroked out, since you modified the reward contract to not check for validators, correct?

**Comment by jannikluhn** [comment]
I don't understand criteria 1 and 2. 3 and 4 is done.

**Comment by weilbith** [comment]
I agree they are not well understandable. Unfortunately I was on vacation during the refinement of this.
So I understood it as we deploy the `ValidatorSet` contract and connect it to the bridge. Doens't make sense I guess...?

**Comment by weilbith** [comment]
@andfletcher could you clarify the mentioned criteria?

**Comment by weilbith** [comment]
We clarified the open questions during sprint meeting and figured out that we have done them already.
