### ISSUE TITLE
Make quickstart copy out the docker-compose file

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#470]
Let the quickstart script copy the docker-compose file to the host, so that you can run docker-compose commands and change which images are used. 

Check if we can use a user and main docker-compose file to make it more easy to override settings. 
Check how this works together with the bridge toml.

**Comment by weilbith** [comment]
It seems like this issue has been solved with #486

> Check if we can use a user and main docker-compose file to make it more easy to override settings.

Is this solved/answered?

**Comment by berndbohmeier** [comment]
Done
