### ISSUE TITLE
Fix: Wait for home chain to be fully synced

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#473]
When restarting the bridge it sent out a lot of confirmation for already completed transfers. This seems to be because we do not properly wait for the home node to be synced.

**Comment by schmir-at-bb** [comment]
We should not wait at startup and instead ask for the syncing status in the event_fetcher (unless there is some other kind of bug, which I don't think is the case).

**Comment by berndbohmeier** [comment]
No, I think it is just that we do not wait properly for it to be synced, and we already saw then at other places that the getLogs endpoint might just return no events.

**Comment by berndbohmeier** [comment]
So waiting in the fetcher should be the right thing, yes.

**Comment by schmir-at-bb** [comment]
> No, I think it is just that we do not wait properly for it to be synced, and we already saw then at other places that the getLogs endpoint might just return no events.

But that would be a different issue that you want to solve. If a light client returns no events if it's not fully synced, we can take a look at it in another issue.
 
> So waiting in the fetcher should be the right thing, yes.

No, *waiting* is the wrong thing to do. Just ask for the syncing status before putting the FetcherReachedHeadEvent on the queue is enough.  (We can either not put the event on the queue if the node is still syncing or put an additional event on the queue with the syncing status, or pass the syncing status inside the event)

That way we will still be able to process events, but we will still not send out confirmations.
