### ISSUE TITLE
Foreign light node gets stuck

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#474]
On our bridge testsetup some of the nodes did not confirm an transfers after a while, and it looked like the light client was stuck and did not sync properly. 
The one I checked for example was stuck on block 1452531 on Görli

**Comment by berndbohmeier** [comment]
For testing why this happens we decided we should test two things:
 - if we have a lightclient on ethereum mainnet, does it also get stuck?
 - if we have a node on gorli which serves lightclients, does that help?

**Comment by schmir-at-bb** [comment]
I wasn't able to successfully restart goerli node in light mode. It synchronizes no new blocks.

**Comment by berndbohmeier** [comment]
We switched to geth, that seems to work stable.
