### ISSUE TITLE
Add option to connect to infura to auction-deploy CLI tool

### ISSUE THREAD

**Issue by schmir-at-bb** [trustlines-protocol/blockchain#48]
We do not want to synchronize a main chain node for the auction and instead would like to use https://infura.io/ to deploy and manage the auction contracts.

web3py has the functionality to connect to infura:
https://web3py.readthedocs.io/en/stable/providers.html#infura-mainnet

We need to integrate that into the CLI client.

**Comment by schmir-at-bb** [comment]
In order to use infura, one has to create an account and create an infura project. Infura will generate a project specific URL that can be used to access infura. It does provide a JSONRPC compatible interface that can already be used with the auction deploy tool. At the moment we have to provide the `--nonce` argument to have it work. I'm not sure if this is a problem we wouldn't have when running our own node.

I've successfully deployed the auction contracts with the following command:
```
auction-deploy deploy --jsonrpc https://kovan.infura.io/v3/f9... --keystore ~/privkey.json --release-block 11_000_000 --nonce 53
```

**Comment by schmir-at-bb** [comment]
I'm moving this to in review. Unless more issues pop up, I consider this done.

**Comment by berndbohmeier** [comment]
Okay. Done then.
