### ISSUE TITLE
Unify blockchain image config

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#493]
At the moment we have several places where we have config for parity of the trustlines blockchain image. (`user-config.toml`, `validator-config.toml`(not used), inline template strings and parity args in `parity-wrapper.sh`) We should unify that and have all the config in one place)

**Comment by weilbith** [comment]
Note:
Currently the build of the node image is broken. While the `user-config.toml` refers to the `laika-spec`, does the `Dockerfile` name it with the old "neutra" name `trustlines-spec`. This problem should be solved within this issue.

**Comment by weilbith** [comment]
The above note will be solved by PR #495 :heavy_check_mark:
