### ISSUE TITLE
Send auction ether to locking contract

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#5]
The validator contract should be able to send `123 * lowest_bid` ether to the locking contract along with the winner addresses once the auction is over.

**Comment by schmir** [comment]
The current plan is:
- remove the deposit function from the `DepositLocker` contract
- add a `registerParticipant` function, which registers a participant. This will be called from the auction contract, when a successful bid came in with the participants address.
- make sure the above `registerParticipant` function can only be called from the auction contract , therefore we need to store the address of the auction contract inside the deposit locker contract.
- add a function `depositBids` to the auction contract that transfers `NUMBER_OF_PARTICIPANTS * slot_price` eth to the deposit contract
- add a function to the depositContract that takes those bids and distributes it to the registered participants

**Comment by cducrest** [comment]
> add a function to the depositContract that takes those bids and distributes it to the registered participants. This should only be callable from the auction contract.

I don't believe you need to distribute the bids to the registered participants in the deposit contract.
You can more easily keep track of who is able to withdraw deposit by initiating this with the successful bidders and removing addresses as they withdraw their deposits or get slashed.

I will add that the auction contract needs to know the address of the locker contract to know what contract to call.

**Comment by schmir** [comment]
Thanks @cducrest. I'll start with the changes to the DepositLocker contract then.

**Comment by schmir** [comment]
The deposit locker changes are in this PR https://github.com/trustlines-protocol/blockchain/pull/16

**Comment by berndbohmeier** [comment]
Done
