### ISSUE TITLE
Document bootstrap nodes settings

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#515]
Document bootstrap node settings with short description of reason for every setting if there is any.

**Comment by cducrest** [comment]
The idea would be to disable what we do not use and increase the min/max number of peers. The actual number were given to me through my dreams.

```
[parity]
auto_update = "none"
no_download = true
identity = "bootnodeX"

[network]
# Parity will try to maintain connection to at least 50 peers.
min_peers = 50
# Parity will maintain at most 150 peers.
max_peers = 150
# Parity will maintain additional 5 peers for snapshot sync.
snapshot_peers = 5

[rpc]
# You won't be able to interact with Parity using JSON-RPC over HTTP.
disable = true

[websockets]
# UI won't work and WebSockets server will be not available.
disable = true

[ipc]
# You won't be able to use IPC to interact with Parity.
disable = true

[secretstore]
# You won't be able to encrypt and decrypt secrets.
disable = true
```

If we can run them with the `--no-hardware-wallets` command would be nice. I did not find a way to have that within the config.

**Comment by schmir-at-bb** [comment]
I think we need the RPC interface if we want to report to netstats (or websockets even?).
I'd rather pass a bunch of command line arguments to parity instead of adapting the configuration file.

**Comment by cducrest** [comment]
Then I would use the following command: `--auto-update=none --no-download --identity=bootnodeX --min-peers=10 --max-peers=150 --snpashot-peers=5  --no-ipc --no-secretstore --no-hardware-wallets`

**Comment by schmir-at-bb** [comment]
The configuration can be found here:
https://github.com/trustlines-network/deployment-config/blob/master/ansible/bootnode.yml#L70-L83


I added:

 --allow-ips=public (parity will not connect to private networks)
--nat=extip:{{floating_ip}}  because that is the IP the other will use to connect to it.

**Comment by schmir-at-bb** [comment]
We need to decide if we want to run with `--no-warp`.

**Comment by schmir-at-bb** [comment]
`--no-warp` it is. The whole configuration lives inside the deployment-config repository.
