### ISSUE TITLE
Let bridge retry rpc request also at startup

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#517]
The bridge seems to crash during the initial wait phase because it does not retry failed requests.

**Comment by jannikluhn** [comment]
Can you clarify which RPC requests you mean @schmir-at-bb ? The wait-until-sync phase seems to be covered already. What is not is the contract validation, but since this only takes place after waiting for the nodes to be synced already I doubt this was the issue you experienced.

**Comment by schmir-at-bb** [comment]
AFAICT it was the contract validation.
