### ISSUE TITLE
Deploy foreign bridge contracts for Laika

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#536]
Deploy the foreign bridge contracts on Görli for the Laika bridge. 
Pre mint 80 Million Tokens of Test Trustlines Token (TTT)
Deploy the real contracts. 

Pre mint the token to an address we as a team have access to. 

Verify the contracts on etherscan.

**Comment by weilbith** [comment]
- the verified [Test Trustlines Token](https://goerli.etherscan.io/token/0xc59636130365C6723e760Dd55436BE54495c6133)
- the verified [Foreign Bridge](https://goerli.etherscan.io/address/0x22bB53A8dC4EbeFE66451E0B65878afe8Aa13B29) at #1596703 (for the bridge config)

The pre-mint token holder (`0xbbc7dA0cD394E1bF954E669e407E044BeF7d6F80`) can be accessed via the `bridge-testing` tool and the new `config-ttt.toml` file (checkout [this PR](https://github.com/trustlines-network/bridge-testing/pull/4)).
The pre-mint token holder account has been shared via faucet and has already done one test transfer to the foreign bridge contract.

**Comment by weilbith** [comment]
Okay, I just quickly need to redo it. I messed up the quantity by the factor of the decimals. :expressionless: 
I will simply update the above comment and add another comment if this done.

**Comment by weilbith** [comment]
Update already done. _Etherscan_ was smart enough to register that this is same code as before and automatically verified it by `Similar Match`.

**Comment by weilbith** [comment]
I will close this issue if the above mentioned PR for the account stuff got accepted.

**Comment by berndbohmeier** [comment]
And please check your setup, you are using the wrong compiler version. v0.5.12

**Comment by berndbohmeier** [comment]
done
