### ISSUE TITLE
Let quickstart create a small readme that explains the setup

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#573]
Let the quickstart create a readme that explains some basic actions about what you can do
e.g use `docker-compose ps` to check for running services, 
use `docker-compose down` to shut the services down. 

For more information refer to docker-compose or docker documentation.

**Comment by cducrest** [comment]
Readme:

You can check which services are running with `docker-compose ps`.

For more information see the docker-compose documentation via `docker-compose --help` or online at https://docs.docker.com/compose/. You can also check the docker documentation via `docker --help` or online at https://docs.docker.com/engine/reference/commandline/docker/
