### ISSUE TITLE
Fix outdated bridge client setup with docker-compose

### ISSUE THREAD

**Issue by weilbith** [trustlines-protocol/blockchain#608]
The setup of the bridge client with the two blockchain nodes via the provided docker-compose does not work as it is anymore. There are multiple things to fix:

  - use the correct images and point to the releases and `*-next` versions (it even states that there is no tlbc at the moment)
  - use the _Geth_ client as foreign node as we do for the quickstart, since the _Parity_ light mode does not work in a reliable manner
  - the bridge client is not configurable via environment variables anymore, even if the compose setup and documentation still try to use such

Possible improvements:
  - maybe we can use the native `docker-compose` extend feature to split the configuration in a more convenient way for the user (this gets rid of mixing different files manually via CLI)

**Comment by schmir-at-bb** [comment]
This is about the `tools/bridge/docker` directory, right? I propose just removing that and be done with it. 

I see no reason to keep it, I at least didn't use it.

**Comment by weilbith** [comment]
Hmm. Actually you are right. It will be "hard" to maintain that and it does not add much value. So I'll go for removing that. The README in the root directory also includes instructions how to setup all components manually via Docker. That must be enough. So I'll go for removing that.
