### ISSUE TITLE
Store history of finalized changes into the validator set contract

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#62]
System calls by Parity do not emit events. There we have to store the history of validator set changes to the contracts state.

**Related**
- https://github.com/trustlines-network/project/issues/429

**Comment by jannikluhn** [comment]
```
// do not modify this function, aura will likely bug
```

Looks like we shouldn't do this at all.

**Comment by cducrest** [comment]
This comment comes from me, we can try to modify it and see what happens
