### ISSUE TITLE
auction-deploy status does not work if DepositLocker is not initialized

### ISSUE THREAD

**Issue by schmir-at-bb** [trustlines-protocol/blockchain#69]
auction-deploy status will not work if the DepositLocker is not initialized. It will try to call functions on the slasher contract, which address is zero in that case.

**Comment by berndbohmeier** [comment]
how does the error look like? Is it specific to the 0x address or that the function does not exist? For the later we can not really ensure that it works, as we dont check that the right contract was deployed.
