### ISSUE TITLE
Try upgrading solidity to 0.5.7 and collect what needs to be changed. 

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#83]

**Comment by schmir-at-bb** [comment]
The referenced PRs above should be  nearly everything that needs to be changed.

**Comment by schmir-at-bb** [comment]
The changelog makes me feel like we should stay on 0.4.x: https://github.com/ethereum/solidity/blob/develop/Changelog.md

**Comment by berndbohmeier** [comment]
I fail to see what you changed, you only where forced to make stuff explicit, no?
So I would think we should update.

**Comment by schmir-at-bb** [comment]
> I fail to see what you changed, you only where forced to make stuff explicit, no?

Yes. The commit messages are fairly detailed.You should probably read them. 

> So I would think we should update.

Well, the changes being small was a requirement for us to do it. That should not mean that we have to do it. After reading the solidity changelog, I also feel like we should use the latest released version if we switch to 0.5.x. (0.5.8 does contain some important bugfixes).

**Comment by berndbohmeier** [comment]
I read them. Making the data location explicit is not a change for me. The data location was the same, only you now have to declare it.

**Comment by schmir-at-bb** [comment]
> I read them. 

sorry, for implying the opposite.

> Making the data location explicit is not a change for me. The data location was the same, only you now have to declare it

yes, I agree. The real change is the different compiler version being used.

(as an aside I remember spending at least a day on a bug in gcc I hit, when I changed the type of a parameter from `double` to `const double`. That was 18 years ago. Not sure what that tells us.Probably that I'm old)

**Comment by schmir-at-bb** [comment]
we changed the builder image and contract-deploy-tools to support solidity 0.5.8. A PR is in review that changes the solidity version to 0.5.8 in the blockchain repo.
