### ISSUE TITLE
Have two bootstrap nodes running

### ISSUE THREAD

**Issue by jannikluhn** [trustlines-protocol/blockchain#89]
On Digital Ocean in two different regions

They should auto update

The RPC interface should not be exposed

We should be notified if they stop running.

**Comment by schmir-at-bb** [comment]
We have two bootnodes in Singapore and Amsterdam running at digital ocean.
They are already part of the trustlines spec file.

See https://github.com/trustlines-network/deployment-config#trustlines-bootnode- for more details.
