### ISSUE TITLE
Deploy validator set contract to the Trustlines testnet

### ISSUE THREAD

**Issue by jannikluhn** [trustlines-protocol/blockchain#92]
Use the validator set currently used in the testnet.

**Comment by cducrest** [comment]
Done, validator set address: 0x352B8FaC58c743FA2aaA086e20d0bF3789774d46
Validators are the same as the current validator set: 
0x876ac3250fb8cebe6e33b7dfa64fb25b18795f95,
0xa278ce59851441faf42070468d713d1389da0183,
0x4c88880aee6d29a4cd0c3ff7df813a9743c13db4,
0xc8fce36cced702809203c9121ee6767a376786cc,
0x27e6925dd78fabcc9d95da178f9ebb986fa66fdb,
0x6c2c0005dbe0f061db93949dd4c876bf3c9bbe5e,
0xb01b4f67d87b98cb1edb1572b1a3cda3191320a6,
0xf7921f0bca54d81692656d357f88d51effd9e45a,
0x864123e2747676b69abc4152b3c5bb7c6dbf66e0,
0x251968f7b5cd540814dc2b4e08634ae7fd59c9b1,
0xd3a22ca447f3f0b1b911b06034438bb2629af00e,
0xe399d154168b8e9043589d4e8128d07f63c75d78,
0xb185ef607850d0e5a9b78c150dbc410e97b18870,
0x557143ab458f77da5e99a0de7060ab4037a8adbb,
0x881f68fb5d33fba220b9e98d31526ed1b76cec7a,
0xa99c08b845c05ee472928ae66c1b97ee3e4d5d09,
0x3150ff61dbe459158615e519250d5a92029d008e,
0x7ccb24b3900562d861faa166de1a86ec0e14d0b9,
0x804717e84632ce86b8e72fc909247234f41f980b
