### ISSUE TITLE
Communicate upcoming hard fork to community

### ISSUE THREAD

**Issue by jannikluhn** [trustlines-protocol/blockchain#93]
Write down hard fork changes (block number, validator contract).

Discuss with comms team which should write Reddit post

Also announce in Rocket Chat channel that Reddit post exists.

**Comment by cducrest** [comment]
We will fork the Trustlines test chain on block 2717171 to change the validator set handling from a list to a contract. The validators in themselves will not change, each addresses present in the current validator list will be present in the contract. The contract address is 0x352B8FaC58c743FA2aaA086e20d0bF3789774d46. You can see the new chain spec file to be used at https://github.com/trustlines-protocol/blockchain/blob/7ce8d689efee5cce672556c41ffbadec3bf6f0a6/config/trustlines-spec.json.

The ValidatorSet contract deployed corresponds to https://github.com/trustlines-protocol/blockchain/blob/7ce8d689efee5cce672556c41ffbadec3bf6f0a6/contracts/contracts/ValidatorSet.sol

You can check the validator set by calling the getValidators() function on the contract. Alternatively, the validator-set-deploy cli tool can be used to print the current validators of the set: https://github.com/trustlines-protocol/blockchain/tree/7ce8d689efee5cce672556c41ffbadec3bf6f0a6/validator-set-deploy

Validators running watchtower on the trustlines testnet docker image (validators that used the quickstart script) will automatically update to use this new fork.

**Comment by jannikluhn** [comment]
> We will fork the Trustlines test chain

"We will distribute an update that would fork ..."

Would also be nice to have an explanation in there why we do this. "In the current iteration of the testnet, the list of validators is statically defined. With the update, we switch to a so called validator set contract. This allows the network to dynamically modify the validator set according to the rules of a smart contract."

Also, we should add that this means equivocating validators can now be removed.

**Comment by weilbith** [comment]
> Validators running watchtower on the trustlines testnet docker image (validators that used the quickstart script) will automatically update to use this new fork.

Do we "immediately" build and push this new _Docker_ image after posting this or do we wait for some discussion/feedback?

**Comment by cducrest** [comment]
We tried having this discussion (about we do we do) many times. To me it is fine to push this new Docker image, if validators disagree they can remove the watchtower. I think we should provision for pushing the image on Friday and announce it.

**Comment by cducrest** [comment]
The process was handled to comms.
