### ISSUE TITLE
Check if watchtower can work with different tags than latest to update image

### ISSUE THREAD

**Issue by jannikluhn** [trustlines-protocol/blockchain#95]
We need to check that if we upload an image to a different tag that it will be ignored and not replace an existing one.

**Comment by cducrest** [comment]
I checked this by doing the following:
- create a docker hub repository: `cducrest/test_watchtower_behaviour`
- tag a random looping image with firstupload: `docker tag fce289e99eb9 cducrest/test_watchtower_behaviour:firstupload`
- push it: `docker push cducrest/test_watchtower_behaviour`
- run it: `docker run cducrest/test_watchtower_behaviour:firstupload`
- run watchtower with update time of 20 sec: `docker run --name watchtower -v /var/run/docker.sock:/var/run/docker.sock v2tec/watchtower -i 20`
- tag an hello-world image with secondupload: `docker tag 88716ad5224c ducrest/test_watchtower_behaviour:secondupload`
- push it: `docker push cducrest/test_watchtower_behaviour`
- wait for watchtower to potentially detect something

Nothing was detected and watchtower showed no output, the looping image kept on producing output and was not stopped.

To confirm the behaviour, I did the following:
- retag the hello world image with firstupload: `docker tag 88716ad5224c ducrest/test_watchtower_behaviour:firstupload`
- push it: `docker push cducrest/test_watchtower_behaviour`
- now I see the watchtower docker container saying `"Found new cducrest/test_watchtower_behaviour:firstupload image"`
- it also logs that it stops and restarts the image
- I confirm the looping image is stopped and hello-world ran

**Comment by schmir-at-bb** [comment]
@cducrest just explained to me that 
```
docker push cducrest/test_watchtower_behaviour
```
pushes all of the tags to dockerhub. I previously assumed wrongly it would only push the `latest` tag.

This means we should make sure that we always explicitly specify a tag when pushing images, and that the above is valid. We will be able to push to different tags without any bad effects.
