### ISSUE TITLE
Figure out update process of tlbc image on docker hub

### ISSUE THREAD

**Issue by jannikluhn** [trustlines-protocol/blockchain#96]
How do we control who can update and that we have the right image.

**Comment by schmir-at-bb** [comment]
The canonical way to do it would be via uploading from circleci.  We can publish pre releases on the prerelease branch, test them as much as we like, and then merge them to the release branch if we think they are ready.

Problems with the canonical way:
1. a new release will be built when building from the release branch, i.e. the image may not be 100% identical to the pre-release that got tested.
2. everyone able to push to the repo may be able to see the `DOCKER_PASSWORD`.  We could prevent that by forbidding direct pushes.

@berndbohmeier Anything else I forgot?

**Comment by berndbohmeier** [comment]
Yes. For 2 we could check out https://circleci.com/docs/2.0/contexts/#restricting-a-context

**Comment by berndbohmeier** [comment]
We 1. we could add an approval job (https://circleci.com/docs/2.0/contexts/#approving-jobs-that-use-restricted-contexts) right before the upload step, and then he would manually verify that the hash of the to be uploaded image is the same.

**Comment by berndbohmeier** [comment]
So build on prerelease would be the same, on release the docker credentials for docker hub would be restricted and we would have a an approval job where you would compare the print out hash of the image with the one uploaded from the prerelease branch.
@schmir-at-bb What do you think?

**Comment by schmir-at-bb** [comment]
> Yes. For 2 we could check out https://circleci.com/docs/2.0/contexts/#restricting-a-context
> I think preventing direct pushes will not change it, because you could just change the circle ci config so that it builds on a different branch.

I meant restricting push access to all branches, i.e. we would have to open PRs from forks to get commits into the repository.

> So build on prerelease would be the same, on release the docker credentials for docker hub would be restricted and we would have a an approval job where you would compare the print out hash of the image with the one uploaded from the prerelease branch.

That sounds reasonable. Let's try it.

**Comment by schmir-at-bb** [comment]
Unfortunately, it's not that easy. Even a single `COPY` command will result in a different image, since we end up with different creation times if the image build cache isn't available on the machine.
I tried to save the image with `docker save` and load it later. That doesn't get you the whole cache.

Apparently that would have worked some time ago, but doesn't anymore.

https://russt.me/2017/08/moving-or-distributing-your-docker-build-cache/ contains instructions on how to save the complete build cache (but that would require us to store it somewhere).

**Comment by schmir-at-bb** [comment]
The above instructions to save the build cache do work.

https://circleci.com/docs/2.0/docker-layer-caching/ will not fix the issue reliably. From the docs:
```
One DLC volume can only be attached to one machine or Remote Docker job at a time. If one DLC volume exists but two jobs that request DLC are launched, CircleCI will create a new DLC volume and attach it to the second job. From that point on the project will have two DLC volumes associated with it. This applies to parallel jobs as well: if two machine jobs are run in parallel, they will get different DLC volumes.

Depending on which jobs the volumes are used in, they might end up with different layers saved on them. The volumes that are used less frequently might have older layers saved on them.

The DLC volumes are deleted after 14 days of not being used in a job.
```

**Comment by schmir-at-bb** [comment]
I can't get the caching to work with the first command after `COPY from parity`. It didn't cache an 'EXPOSE' command. I reordered the command and then it didn't cache a COPY command.

I think it's better to stop at this point.
