### ISSUE TITLE
Auction smart contract review

### ISSUE THREAD

**Issue by karlb** [trustlines-protocol/blockchain#97]
I've read through the auction SCs at revision a028c335c7d50e60b01e10941fc1c4311fc46074, which included the files

* DepositLocker.sol
* ValidatorAuction.sol
* ValidatorSlasher.sol
* EquivocationInspector.sol (just a quick glance at this one)

## Style issues
* Functions always return `true`, so they could just return void instead (`DepositLocker.sol`)
* Default functions seem unnecessary e.g. `function() external {}`. I've been told they might be required in for solc releases. (`DepositLocker.sol`, `ValidatorAuction.sol`)
* `init` sets `owner = address(0)`, which serves no purpose because the `initialized` variable is already used to prevent calling this function twice. (`DepositLocker.sol`)

## Comments on functionality
* The contracts use time instead of block numbers. This provides consistent behaviour when block times change, but might allow bidders to reduce their bids slightly by manipulating the time by some seconds. This effect is probably small enough to be unnoticeable, though.
* `priceAtElapsedTime` contains magic constants which makes it harder to understand the exact behaviour and intention. The results look plausible and I could not find a way to overflow any value.
* The EquivocationInspector assumes specific layout of the input data which I can't properly understand just from looking at the contract. The `/ STEP_DURATION` division looks suspicious to me and might cause false positives for certain inputs. If can't judge whether those inputs are created during proper operation, tough.

**Comment by berndbohmeier** [comment]
We reacted to the feedback with the following actions:

> Functions always return true, so they could just return void instead (DepositLocker.sol)

We removed the return true

> Default functions seem unnecessary e.g. function() external {}. 

We removed the functions

> init sets owner = address(0), which serves no purpose because the initialized variable is already used to prevent calling this function twice. (DepositLocker.sol)

We will keep this for clearity and safty reasons. 

> The contracts use time instead of block numbers. This provides consistent behaviour when block times change, but might allow bidders to reduce their bids slightly by manipulating the time by some seconds. This effect is probably small enough to be unnoticeable, though.

We are fine with this and will not change it. 

> priceAtElapsedTime contains magic constants which makes it harder to understand the exact behaviour and intention. The results look plausible and I could not find a way to overflow any value.

The constants are magic as there is not other reason than that they give us the right price function so we will keep this. 


> The EquivocationInspector assumes specific layout of the input data which I can't properly understand just from looking at the contract. The / STEP_DURATION division looks suspicious to me and might cause false positives for certain inputs. If can't judge whether those inputs are created during proper operation, tough.

We scheduled another internal audit for the rlp reader.
